# Generated by Django 5.2.2 on 2025-08-15 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_create_roles_permissions_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('OWNED', 'Propias'), ('WORKCELL', 'Célula'), ('ALL', 'Todas'), ('NONE', 'Ninguna')], max_length=20)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Menor número = mayor prioridad al resolver conflictos')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_policy', to='auth.group', unique=True)),
            ],
            options={
                'verbose_name': 'Política de Rol',
                'verbose_name_plural': 'Políticas de Rol',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
