# Generated by Django 5.2.2 on 2025-08-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepolicy',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
