# Generated by Django 5.2.2 on 2025-09-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_create_roles_permissions_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='classification',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PROSPECTO', 'Prospecto')], default='ACTIVO', max_length=10, verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='classification',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PROSPECTO', 'Prospecto')], default='ACTIVO', max_length=10, verbose_name='Clasificación'),
        ),
    ]
