# Generated by Django 5.2.2 on 2025-07-01 18:32

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_create_roles_permissions_catalog'),
        ('opportunity', '0003_seed_initial_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_data', to='opportunity.opportunity')),
                ('purchase_status_type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_status_type_data', to='catalog.purchasestatustype', verbose_name='Tipo de estado de compra')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
