# Generated by Django 5.2.2 on 2025-07-09 21:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_create_roles_permissions_catalog'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder 100 caracteres.', 'unique': 'Este nombre de contacto ya existe.'}, max_length=100, unique=True, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, error_messages={'max_length': 'La dirección no puede exceder 255 caracteres.'}, max_length=255, null=True, verbose_name='Dirección')),
                ('email', models.CharField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Debe ser un correo electrónico válido')], verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número debe contener al menos 10 dígitos numéricos.', regex='^\\d{10,}$')], verbose_name='Teléfono')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.city', verbose_name='Ciudad')),
                ('clients', models.ManyToManyField(blank=True, related_name='contact', to='client.client', verbose_name='Clientes')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.job', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contact_contacts',
            },
        ),
    ]
