# Generated by Django 5.2.2 on 2025-08-07 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_create_roles_permissions_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Debe ser un correo electrónico válido')], verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Debe ser un correo electrónico válido')], verbose_name='Correo electrónico'),
        ),
    ]
