# Generated by Django 5.2.2 on 2025-06-06 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.city')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contact.contact')),
                ('status_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.statusopportunity')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'db_table': 'opportunity_opportunities',
            },
        ),
        migrations.CreateModel(
            name='ComercialActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oportunity_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Actividad comercial',
                'verbose_name_plural': 'Actividades comerciales',
                'db_table': 'opportunity_comercial_activities',
            },
        ),
    ]
