# Generated by Django 5.2.2 on 2025-07-01 16:45

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_seed_initial_catalog'),
        ('contact', '0002_create_roles_permissions_contact'),
        ('project', '0002_create_roles_permissions_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('closing_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Porcentage de cierre')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('number_fvt', models.CharField(max_length=100, unique=True, verbose_name='Formato de venta')),
                ('date_reception', models.DateTimeField(blank=True, verbose_name='Fecha de recepción')),
                ('sent_date', models.DateTimeField(blank=True, verbose_name='Fecha de enviado')),
                ('date_status', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del estado')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contact.contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.currency')),
                ('opportunityType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.opportunitytype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.project')),
                ('status_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.statusopportunity')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'db_table': 'opportunity_opportunities',
            },
        ),
        migrations.CreateModel(
            name='LostOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('lost_opportunity_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.lostopportunitytype', verbose_name='Tipo de oportunidad perdida')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lost_opportunity_data', to='opportunity.opportunity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('cost_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offer_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('earned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_closing_date', models.DateTimeField(blank=True, verbose_name='Fecha de cierre de orden')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance_data', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Dato financiero de la oportunidad',
                'verbose_name_plural': 'Datos financieros de las oportunidades',
                'db_table': 'opportunity_finance_opportunities',
            },
        ),
        migrations.CreateModel(
            name='CommercialActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_scheduled', models.DateTimeField(auto_now_add=True, verbose_name='Fecha programada')),
                ('description', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado')),
                ('opportunities', models.ManyToManyField(blank=True, related_name='commercial_activities', to='opportunity.opportunity', verbose_name='Oportunidades asociadas')),
            ],
            options={
                'verbose_name': 'Actividad comercial',
                'verbose_name_plural': 'Actividades comerciales',
                'db_table': 'opportunity_commercial_activities',
            },
        ),
        migrations.CreateModel(
            name='PurchaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('lostOpportunityType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.lostopportunitytype', verbose_name='Tipo de oportunidad perdida')),
                ('purchase_status_type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_status_type_data', to='catalog.purchasestatustype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
