# Generated by Django 5.2.2 on 2025-08-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_create_roles_permissions_client'),
        ('opportunity', '0003_seed_initial_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalopportunity',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.client'),
        ),
    ]
