# Generated by Django 5.2.2 on 2025-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_historicalopportunity_client_opportunity_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitydocument',
            name='sharepoint_url',
            field=models.URLField(max_length=1000),
        ),
    ]
