# Generated by Django 5.2.2 on 2025-08-08 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_create_roles_permissions_catalog'),
        ('opportunity', '0005_alter_opportunitydocument_sharepoint_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalopportunity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.currency'),
        ),
    ]
