# Generated by Django 5.2.2 on 2025-08-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0006_alter_historicalopportunity_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeopportunity',
            name='oc_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de orden de compra cliente'),
        ),
    ]
