# Generated by Django 5.2.2 on 2025-08-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_create_roles_permissions_catalog'),
        ('opportunity', '0007_financeopportunity_oc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalopportunity',
            name='lost_opportunity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.lostopportunitytype'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lost_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.lostopportunitytype'),
        ),
        migrations.DeleteModel(
            name='LostOpportunity',
        ),
    ]
