# Generated by Django 5.2.2 on 2025-08-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0008_historicalopportunity_lost_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeopportunity',
            name='cash_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de contado'),
        ),
        migrations.AddField(
            model_name='financeopportunity',
            name='credit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de crédito'),
        ),
        migrations.AddField(
            model_name='historicalopportunity',
            name='number_items',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de partidas'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='number_items',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de partidas'),
        ),
        migrations.AlterField(
            model_name='historicalopportunity',
            name='closing_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de cierre'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='closing_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de cierre'),
        ),
    ]
