# Generated by Django 5.2.2 on 2025-08-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0009_financeopportunity_cash_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalopportunity',
            name='date_limit_send',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha límite de envío'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='date_limit_send',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha límite de envío'),
        ),
    ]
