# Generated by Django 5.2.2 on 2025-08-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0010_historicalopportunity_date_limit_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalopportunity',
            name='order_closing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre de orden'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='order_closing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre de orden'),
        ),
    ]
