# Generated by Django 5.2.2 on 2025-06-18 18:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_initial_catalog'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder 100 caracteres.', 'unique': 'Este nombre de proyecto ya existe.'}, max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.businessgroup', verbose_name='Grupo empresarial')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.client', verbose_name='Cliente')),
                ('project_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.projectstatus', verbose_name='Estatus del proyecto')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.specialty', verbose_name='Especialidad')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.subdivision', verbose_name='Subdivisión')),
                ('work_cell', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.workcell', verbose_name='Célula de trabajo')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'project_projects',
            },
        ),
    ]
