# Generated by Django 5.2.2 on 2025-06-07 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('business_groups', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.businessgroup', verbose_name='Grupo empresarial')),
                ('project_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.projectstatus', verbose_name='Estatus del proyecto')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.speciality', verbose_name='Especialidad')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.subdivision', verbose_name='Subdivisión')),
                ('work_cell', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.workcell', verbose_name='Célula de trabajo')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'project_projects',
            },
        ),
    ]
