# Generated by Django 5.2.2 on 2025-06-07 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder 100 caracteres.', 'unique': 'Este grupo empresarial ya existe.'}, max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Grupo empresarial',
                'verbose_name_plural': 'Grupos empresariales',
                'db_table': 'catalog_business_groups',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder 100 caracteres.', 'unique': 'Esta ciudad ya existe.'}, max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'catalog_city',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder 100 caracteres.', 'unique': 'Este período ya existe.'}, max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'db_table': 'catalog_periods',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder 100 caracteres.', 'unique': 'Este estado ya existe.'}, max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado del proyecto',
                'verbose_name_plural': 'Estados del proyecto',
                'db_table': 'catalog_project_status',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder 100 caracteres.', 'unique': 'Esta especialidad ya existe.'}, max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'catalog_specialities',
            },
        ),
        migrations.CreateModel(
            name='StatusOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder 100 caracteres.', 'unique': 'Este estado de oportunidad ya existe.'}, max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado de la oportunidad',
                'verbose_name_plural': 'Estados de la oportunidad',
                'db_table': 'catalog_status_opportunities',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder 100 caracteres.', 'unique': 'Esta división ya existe.'}, max_length=100, unique=True, verbose_name='Nombre')),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.businessgroup', verbose_name='Grupo empresarial')),
            ],
            options={
                'verbose_name': 'División',
                'verbose_name_plural': 'Divisiones',
                'db_table': 'catalog_divisions',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder 100 caracteres.', 'unique': 'Esta subdivisión ya existe.'}, max_length=100, unique=True, verbose_name='Nombre')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.division', verbose_name='División')),
            ],
            options={
                'verbose_name': 'Subdivisión',
                'verbose_name_plural': 'Subdivisiones',
                'db_table': 'catalog_subdivisions',
            },
        ),
        migrations.CreateModel(
            name='UDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder 100 caracteres.', 'unique': 'Este nombre de UDN ya existe.'}, max_length=100, unique=True, verbose_name='Nombre')),
                ('users', models.ManyToManyField(blank=True, related_name='udns', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios asignados')),
            ],
            options={
                'verbose_name': 'UDN',
                'verbose_name_plural': "UDN's",
                'db_table': 'catalog_udns',
            },
        ),
        migrations.CreateModel(
            name='WorkCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'El nombre no puede exceder 100 caracteres.', 'unique': 'Este nombre de célula de trabajo ya existe.'}, max_length=100, unique=True, verbose_name='Nombre')),
                ('udn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.udn', verbose_name='UDN')),
                ('users', models.ManyToManyField(blank=True, related_name='workcell', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios asignados')),
            ],
            options={
                'verbose_name': 'Célula de trabajo',
                'verbose_name_plural': 'Células de trabajo',
                'db_table': 'catalog_work_cells',
            },
        ),
    ]
