# Generated by Django 5.2.2 on 2025-06-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_initial_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='udn',
            options={'ordering': ['-name'], 'verbose_name': 'UDN', 'verbose_name_plural': "UDN's"},
        ),
    ]
