# Generated by Django 5.2.2 on 2025-07-01 16:45

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_seed_initial_catalog'),
        ('contact', '0002_create_roles_permissions_contact'),
        ('opportunity', '0001_initial'),
        ('project', '0002_create_roles_permissions_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('observation', models.TextField(blank=True, null=True)),
                ('activity_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de la actividad')),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunity.commercialactivity', verbose_name='Actividad comercial')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contact.contact', verbose_name='Contacto')),
                ('meeting_result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.meetingresult', verbose_name='Resultado de la reunión')),
                ('meeting_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.meetingtype', verbose_name='Tipo de reunión')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opportunity.opportunity', verbose_name='Oportunidad')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registro de actividades',
                'db_table': 'activity_log_activity',
            },
        ),
    ]
